export default {
  name: 'Datsyuk',
  description: 'Stickhandling drills with a Pavel Datsyuk variation',
  difficulty: 3,
  exercises: [
    { name: 'Side Datsyuk' },
    { name: 'Behind Datsyuk' },
    { name: 'Side and Behind Datsyuk' },
    { name: 'Side, 45, Behind Datsyuk' },
    { name: 'Side Datsyuk "L" BH Over Puck 3' },
    { name: 'Side Datsyuk to Wide BH Over Puck 3' },
    { name: 'Side Datsyuk to Wide BH Over Puck 3 FH Over Puck 4' },
    { name: 'Side Datsyuk FH Around Puck 3' },
    { name: 'Side Datsyuk BH Around Puck 3' },
    { name: 'Four Puck Outside In Slide' },
    { name: 'Four Puck Infinity Slide' },
    { name: 'Side Datsyuk to BH Through Vertical Figure 8' },
    { name: 'Front Stickhandle Quick Pull to Side Datsyuk' },
    { name: 'Side Datsyuk Pull Through the Legs' },
    { name: 'Double Side Datsyuk Stack' },
  ],
}
