import { Exercise } from '../types'

export default [
  { name: 'Soft Touch Front', prepareDuration: 10, workDuration: 30 },
  { name: 'Soft Touch Side', prepareDuration: 10, workDuration: 30 },
  { name: 'Soft Touch Backhand', prepareDuration: 10, workDuration: 30 },
  { name: 'Soft Touch Around Side', prepareDuration: 10, workDuration: 30 },
  { name: 'Soft Touch Around Backhand', prepareDuration: 10, workDuration: 30 },
  { name: 'Slide Bottom Hand', prepareDuration: 10, workDuration: 30 },
  { name: 'Roll Puck Front', prepareDuration: 10, workDuration: 30 },
  { name: 'Roll Puck Side', prepareDuration: 10, workDuration: 30 },
  { name: 'Wide Move Front', prepareDuration: 10, workDuration: 30 },
  { name: 'Wide Move Side', prepareDuration: 10, workDuration: 30 },
  { name: 'Wide Move To Soft Touch', prepareDuration: 10, workDuration: 30 },
  { name: 'Forehand Ls', prepareDuration: 10, workDuration: 30 },
  { name: 'Backhand Ls', prepareDuration: 10, workDuration: 30 },
  { name: 'Soft Touch, Pull To Shoot', prepareDuration: 10, workDuration: 30 },
  {
    name: 'Soft Touch, Pull To Fake To Slide',
    prepareDuration: 10,
    workDuration: 30,
  },
  { name: 'Backhand Fake', prepareDuration: 10, workDuration: 30 },
  { name: 'Forehand Fake', prepareDuration: 10, workDuration: 30 },
  { name: 'Fake Snapshot', prepareDuration: 10, workDuration: 30 },
  { name: 'Fake Wristshot', prepareDuration: 10, workDuration: 30 },
  { name: 'Pump Fake', prepareDuration: 10, workDuration: 30 },
  // { name: 'Stick Fake', prepareTime: 10, workTime: 30 },
  { name: 'Backhand Toe Pull', prepareDuration: 10, workDuration: 30 },
  { name: 'Backhand Toe Drag', prepareDuration: 10, workDuration: 30 },
  { name: 'Backhand To Forehand Toey', prepareDuration: 10, workDuration: 30 },
  { name: '5-Points Toe Drag', prepareDuration: 10, workDuration: 30 },
  { name: 'Back To Front Toe Drag', prepareDuration: 10, workDuration: 30 },
  { name: 'Toe Drag Front', prepareDuration: 10, workDuration: 30 },
  { name: 'Toe Drag Side', prepareDuration: 10, workDuration: 30 },
  { name: 'Yo Yo Toe', prepareDuration: 10, workDuration: 30 },
  { name: '8 Start Forehand', prepareDuration: 20, workDuration: 40 },
  { name: '8 Start Backhand', prepareDuration: 20, workDuration: 40 },
  { name: 'Infinity', prepareDuration: 20, workDuration: 40 },
  { name: 'Infinity Toe', prepareDuration: 20, workDuration: 40 },
  { name: 'Side Datsyuk', prepareDuration: 20, workDuration: 40 },
  { name: 'Behind Datsyuk', prepareDuration: 20, workDuration: 40 },
  { name: 'Side And Behind Datsyuk', prepareDuration: 20, workDuration: 40 },
  { name: 'Side Datsyuk L', prepareDuration: 20, workDuration: 40 },
  { name: 'Side Datsyuk To Wide', prepareDuration: 20, workDuration: 40 },
  { name: 'Side Datsyuk To Wide + L', prepareDuration: 20, workDuration: 40 },
  { name: '4 Pucks Slide', prepareDuration: 20, workDuration: 40 },
  { name: '4 Pucks Infinity Slide', prepareDuration: 20, workDuration: 40 },
  { name: 'Side Datsyuk To 8', prepareDuration: 20, workDuration: 40 },
  { name: 'Double Side Datsyuk Stack', prepareDuration: 20, workDuration: 40 },
] as Exercise[]
