name: CI
on: push
jobs:
  build:
    name: Build, test and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn test

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/master' }}
        run: yarn deploy
